[2025-05-07T19:21:18.944+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Simple_Corona_project.Produce_data scheduled__2025-05-07T18:40:00+00:00 [queued]>
[2025-05-07T19:21:18.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Simple_Corona_project.Produce_data scheduled__2025-05-07T18:40:00+00:00 [queued]>
[2025-05-07T19:21:18.956+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-07T19:21:18.972+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): Produce_data> on 2025-05-07 18:40:00+00:00
[2025-05-07T19:21:18.977+0000] {standard_task_runner.py:60} INFO - Started process 67 to run task
[2025-05-07T19:21:18.980+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Simple_Corona_project', 'Produce_data', 'scheduled__2025-05-07T18:40:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/Project_tasks2.py', '--cfg-path', '/tmp/tmpc2_a9agp']
[2025-05-07T19:21:18.983+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask Produce_data
[2025-05-07T19:21:19.044+0000] {task_command.py:423} INFO - Running <TaskInstance: Simple_Corona_project.Produce_data scheduled__2025-05-07T18:40:00+00:00 [running]> on host 1a616c0a8036
[2025-05-07T19:21:19.122+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Simple_Corona_project' AIRFLOW_CTX_TASK_ID='Produce_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T18:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-07T18:40:00+00:00'
[2025-05-07T19:21:19.125+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-07T19:21:19.126+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/***/dags/CoronaProj/python3 API_CALL.py']
[2025-05-07T19:21:19.134+0000] {subprocess.py:86} INFO - Output:
[2025-05-07T19:21:19.138+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /opt/***/dags/CoronaProj/python3: No such file or directory
[2025-05-07T19:21:19.138+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-07T19:21:19.148+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-07T19:21:19.151+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Simple_Corona_project, task_id=Produce_data, execution_date=20250507T184000, start_date=20250507T192118, end_date=20250507T192119
[2025-05-07T19:21:19.165+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task Produce_data (Bash command failed. The command returned a non-zero exit code 127.; 67)
[2025-05-07T19:21:19.195+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-07T19:21:19.217+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
